version: "3.8"

services:
  # PostgreSQL - Stores Airflow metadata and task states
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  # Airflow Webserver - Provides UI for workflow management
  webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW_UID=${AIRFLOW_UID}
      - AIRFLOW_GID=${AIRFLOW_GID}
    volumes:
      - ${AIRFLOW_DAGS_VOLUME}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_VOLUME}:/opt/airflow/logs
      - ${AIRFLOW_PLUGINS_VOLUME}:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: ["webserver"]

  # Airflow Scheduler - Determines when tasks should execute
  scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - webserver
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW_UID=${AIRFLOW_UID}
      - AIRFLOW_GID=${AIRFLOW_GID}
    volumes:
      - ${AIRFLOW_DAGS_VOLUME}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_VOLUME}:/opt/airflow/logs
      - ${AIRFLOW_PLUGINS_VOLUME}:/opt/airflow/plugins
    command: ["scheduler"]

  # Ngrok - Exposes Airflow externally for remote access
  ngrok:
    image: wernight/ngrok
    container_name: airflow_ngrok
    restart: always
    depends_on:
      - webserver
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: ["ngrok", "http", "${NGROK_TARGET}"]
    ports:
      - "4040:4040"  # ngrok monitoring dashboard
