name: Validate Docker Compose

on:
  push:
    branches:
      - main # Validate on push to main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate docker-compose.yml
        run: docker-compose -f docker-compose.yml config
